readding scatter to rm, mc relations
LSSTDESC/CL-SBI pull request #14
Opened 2023-07-20 22:04 UTC by akumgill

intended behavior:
* scatter applied to mc relation and rm relation
* noise dex applied to NFW profiles

behavior before this change:
* noise dex applied to mc relation, rm relation, and NFW profiles

2023-07-27 23:13 UTC, akumgill commented
@cavestruz for review

2023-08-01 21:55 UTC, cavestruz requested changes
There is a merge conflict in the json file - can you resolve this?  Will approve after.

2023-08-02 17:17 UTC, cavestruz approved these changes

2023-08-02 17:17 UTC, merged

2023-08-02 17:17 UTC, cavestruz commented
Great!  Thanks for fixing the merge conflicts.