Pickling inferrers, changing directory structure, updating readme
LSSTDESC/CL-SBI pull request #18
Opened 2023-07-27 22:32 UTC by akumgill

* Adding more intermediate files (i.e. pickled inferrers)
* Updating directory structure so fewer nested directories
* Outputting files to output directory instead of to the config directory
* Updating script running flow to use config IDs instead of filenames
* Updated readme with new running instructions

2023-07-27 23:13 UTC, akumgill commented
@cavestruz for review

2023-08-02 17:24 UTC, cavestruz requested changes
Ah, this one has similar merge conflicts, to one of the previous PRs I think.Can approve once those are resolved.

2023-08-02 17:47 UTC, akumgill commented
resolved merge conflicts

2023-08-04 14:44 UTC, cavestruz requested changes
One request for a pipeline diagram to illustrate the code functionality for the README.

2023-08-04 14:44 UTC, cavestruz commented on README.rst
> +1) Simulation (/configs/simulations) - sim_config tells us about how our simulations were generated/obtained (e.g. the mass-concentration relation used, how much scatter the m-c relation has, the log
These are great!  Can you also put together and put in the readme a visualization of the workflow in a pipeline diagram?

2023-08-04 14:44 UTC, cavestruz commented on README.rst
> +	This will output to the ``outputs/inference/{SIM_ID}.{INFER_ID}.{OBS_ID}.{NUM_SIMS}.{NUM_OBS}`` directory
Nice job on the explicit run-time documentation :-)

2023-08-04 19:42 UTC, akumgill commented
added pipeline flowchart to readme

![pipeline_flowchart](https://github.com/LSSTDESC/CL-SBI/assets/3288799/c3b21cb8-54e2-466d-815f-43d21094bb56)

2023-08-11 17:03 UTC, cavestruz approved these changes
Flow chart looks good :-)

2023-08-11 17:04 UTC, merged