Issue/1/sims module stubs
LSSTDESC/CL-SBI pull request #7
Opened 2023-05-16 16:44 UTC by akumgill

2023-05-16 17:02 UTC, cavestruz requested changes

2023-06-12 21:47 UTC, akumgill commented
requested changes addressed:

- when generating the population, we read from a sim_config and write output files back to the same folder the sim_config is in
- when doing inference, we read the sim_dir which has the output intermediate files from that step and we read the config_dir, from which we get our config params and to which we right the output of inference
- added subselection of mc_pairs based on some user specified cuts we want to make. currently the only option is to include all mc_pairs, but we can change that as we see fit

2023-06-12 22:42 UTC, cavestruz requested changes
Minor changes requested (mostly for naming clarity in the config files).  But, this looks great!

2023-06-12 22:42 UTC, cavestruz commented on configs/example/infer_config.json
For this example config, I noticed that the inference type is sbi, but there are mcmc specific other kwargs, e.g. number of walkers, burn in, etc.  this, I think, should just information to grab a trained sbi inferrer, and/or create it, yes?

2023-06-12 22:42 UTC, cavestruz commented on simulations/example/sim_config.json
Quick requests - the short names require a bit of digging into the examples notebook `simulate_wl_profile.ipynb.`

- [ ] can we change `num_samples` to `num_parameter_samples` -- I first thought this was number of simulated clusters?
- [ ] can we change `num_drawn` to `num_sims` (As, this is number of simulations for training, yes?)

2023-06-14 17:25 UTC, akumgill commented on configs/example/infer_config.json
yes, i have these params passed in to the infer config, but they aren't read/used if we're using SBI. i can add this just to MCMC implementation, but wasn't sure if these were params we'd want to tweak in config. no strong preference either way from my side

2023-06-14 17:38 UTC, akumgill commented
requested changes addressed

2023-06-16 14:42 UTC, akumgill commented on README.rst
> +python examples/mcmc_example.py --config_dir example --sim_dir example
`python examples/mcmc_example.py --infer_dir example --sim_dir example  --obs_dir example`

* Infer dir contains infer_config saying how to do inference (e.g. priors, walkers, burnin, etc) and is the output directory for inference
* Sim dir contains sim_config saying how a given set of simulations in that directory were made
* Obs dir contains obs_config saying how a given set of simulated/real observations were made/obtained

2023-06-23 15:11 UTC, akumgill commented
@cavestruz bump

2023-06-30 14:36 UTC, cavestruz approved these changes
Thanks for making the changes!

2023-06-30 14:36 UTC, merged